[package]
name = "bevy_compute_noise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_flycam = "0.13.0"
bytemuck = "1.15.0"
rand = "0.8.5"